### ISSUE TITLE
关于数据集的划分以及训练的配置的疑问

### ISSUE THREAD

**Issue by August-L-J** [caiyuanhao1998/Retinexformer#64]
大佬你好，我有两个疑问，一个是关于数据集划分的疑问，一个是关于训练的的配置疑问
## 第一个疑问，关于数据集划分的
   为啥按着这样的形式划分LOL_v1的数据集呢？
   在`LOLv1\Test\input`文件夹中，有15张`png`图片
   在`LOLv1\Test\target`文件夹中，有15张`png`图片
   在`LOLv1\Train\input`文件夹中，有485张`png`图片
   在`LOLv1\Train\target`文件夹中，有485张`png`图片
   这样子划分数据集有什么科学依据么？有什么原理呢？
   希望能够得到作者的解答
 ```
    |    |--LOLv1
    |    |    |--Train
    |    |    |    |--input
    |    |    |    |    |--100.png
    |    |    |    |    |--101.png
    |    |    |    |     ...
    |    |    |    |--target
    |    |    |    |    |--100.png
    |    |    |    |    |--101.png
    |    |    |    |     ...
    |    |    |--Test
    |    |    |    |--input
    |    |    |    |    |--111.png
    |    |    |    |    |--146.png
    |    |    |    |     ...
    |    |    |    |--target
    |    |    |    |    |--111.png
    |    |    |    |    |--146.png
 ```

## 第二个疑问，关于训练配置的问题
关于`scheduler`的配置，为什么要使用`CosineAnnealingRestartCyclicLR`算法而不是采用其他的算法呢？(periods: [46000, 104000])  以及`# Split 300k iterations into two cycles. `,`# 1st cycle: fixed 3e-4 LR for 92k iters. `,`# 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.`这些注释设置的科学性在哪呢？是通过什么公式计算的么？ 为什么要采取这样的训练策略而不是其他的训练策略呢？
 希望能够得到作者的解答

  ```
train:
  total_iter: 150000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
```
